primary:
  persistence:
    size: "1Gi"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"

auth:
  postgresPassword: ${admin_password}
  username: ${postgres_user}
  password: ${postgres_password}
  database: ${postgres_db}
